### ISSUE TITLE
Upgrade Argo CD to 2.0

### ISSUE THREAD

**Issue by tobru** [projectsyn/component-argocd#18]
## Context

Upgrade Argo CD to the 2.0 release to stay up-to-date.

The upgrade guide is here: https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/1.8-2.0/

By upgrading the component we also have to upgrade the Argo CD deployment in [steward](https://github.com/projectsyn/steward).

**Comment by tobru** [comment]
Latest release at the time of this comment: https://github.com/argoproj/argo-cd/releases/tag/v2.0.4

**Comment by megian** [comment]
Be aware of we still use Project Syn on OpenShift 3.11 and since K8s 1.11 just supports apiextensions.k8s.io/v1beta1. Can you add a possibility in the component to override the CRD objects, with some for K8s 1.11. Similar to https://github.com/projectsyn/component-backup-k8up/blob/v2.1.4/class/defaults.yml#L21 or if ArgoCD does not work on K8s 1.11 at all. We might require a version lock on <= 2.0.0.

This would also affect steward, not being able to use the version 2.0 by default.

**Comment by bastjan** [comment]
> We might require a version lock to <= 2.0.0.

We'll go with this.

Thanks for the heads up 😊.
